---
# tasks file for kfieldho.kfieldho


- name: My Favorite Tools
  sudo: True                                                                                                                                       
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:                                                                                                                                      
    - tmux
    - git
    - vim

- name: Check to See if My dotfiles are already installed
  stat: path=~/.local/etc/bashrc
  register: base_bashrc 
  changed_when: base_bashrc.stat.exists == False

- name: Check to See if My vimfiles are already installed
  stat: path=~/.vim/vimrc
  register: base_vimrc
  changed_when: base_vimrc.stat.exists == False

- name: Local files                                                                                                                                
  git: repo=https://github.com/kfieldho/localfiles.git dest=/home/vagrant/.local accept_hostkey=yes                                                
  when: base_bashrc.stat.exists == False
                                                                                                                                                 
- name: Vim Config                                                                                                                                 
  git: repo=https://github.com/kfieldho/vimfiles.git dest=/home/vagrant/.vim accept_hostkey=yes                                                    
  when: base_vimrc.stat.exists == False

- name: Check to See if setup has been run
  stat: path=~/.kfieldho
  register: kfieldho_setup
  changed_when: kfieldho_setup.stat.exists == False
                                                                                                                                                 
- name: Configure My Account                                                                                                                       
  command: /home/vagrant/.local/setup.sh   
  when: kfieldho_setup.stat.exists == False
